- src: gzm55.local_openssh_client_permission
  version: 2.0.0
- src: gzm55.local_ssh_known_hosts
  version: 2.0.0
- src: gzm55.ssh_pubkey_login
  version: 2.0.0
- src: gzm55.smart_ssh_pipelining
  version: 2.0.0
- src: gzm55.python_module_bootstrap
  version: 2.0.0
