---
name: ci workflow
"on": push

env:
  ANSIBLE_ROLES_PATH: "..:tests/roles"

jobs:
  test-job:
    name: test the role
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: print versions
      run: |
        set -x
        uname -a
        id
        python3 --version
        pip3 --version
        ansible --version
        docker version

    - name: prepare tests
      run: |
        set -x
        sudo apt install sshpass
        sshpass -V
        pip3 install ansible
        pip3 install -r requirements.txt
        ansible-galaxy install -p tests/roles -r requirements.yml

        # create ssh key, cleanup host fingerprints
        ssh-keygen -N '' -f ~/.ssh/id_rsa
        echo >~/.ssh/known_hosts

    - name: prepare containers for testing
      run: |
        set -x
        # build test image
        docker build -t ansible-test tests

        # listen on localhost:4848
        docker run -p 4848:22 --name alpine-sshd-4848 --hostname alpine-sshd-4848 -d ansible-test
        docker exec -i alpine-sshd-4848 sh -c 'apk add python3'

        # listen on localhost:5848
        docker run -p 5848:22 --name alpine-sshd-5848 --hostname alpine-sshd-5848 -d ansible-test

        # listen on localhost:6848
        # - enable sudo without passowrd
        # - enable pubkey login
        docker run -p 6848:22 --name alpine-sshd-6848 --hostname alpine-sshd-6848 -d ansible-test
        docker exec -i alpine-sshd-6848 sh -c 'echo "%wheel ALL=(ALL) NOPASSWD:"\ ALL >/etc/sudoers.d/wheel'

        # listen on localhost:7848
        # - disable pubkey login
        docker run -p 7848:22 --name alpine-sshd-7848 --hostname alpine-sshd-7848 -d ansible-test
        docker exec -i alpine-sshd-7848 sh -c 'echo "PubkeyAuthentication no" >> /etc/ssh/sshd_config'

        # - listen on localhost:8848
        # - enable sudo with password
        # - disable pubkey login
        docker run -p 8848:22 --name alpine-sshd-8848 --hostname alpine-sshd-8848 -d ansible-test
        docker exec -i alpine-sshd-8848 sh -c 'echo "PubkeyAuthentication no" >> /etc/ssh/sshd_config'
        docker exec -i alpine-sshd-8848 sh -c 'echo "%wheel ALL=(ALL) ALL" >/etc/sudoers.d/wheel'

    - name: syntax check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    - name: TEST
      run: ansible-playbook tests/test.yml -i tests/inventory -vvvvv passB8

  lint-job:
    name: lint codes
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: prepare lint
      run: |
        set -x
        pip3 install -r requirements.txt
        ansible-galaxy install -p tests/roles -r requirements.yml
        pip3 install ansible-lint
        ansible-lint --version
    - name: lint
      run: ansible-lint --show-relpath --exclude tests/roles

  deploy-job:
    name: deploy the role on tag
    runs-on: ubuntu-22.04
    needs: [test-job, lint-job]
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: publish the role to Galaxy
      uses: robertdebock/galaxy-action@1.2.1
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
        git_branch: ${{ github.ref_name }}
